### ISSUE TITLE
Pool fork died

### ISSUE THREAD

**Issue by stestaz** [zone117x/node-cryptonote-pool#106]
Hi,
I'm trying to run the script on my server, I've installed everything (Node 10 too) the npm update is working but when I try to run node init.js  all  worker dies with this error:

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /var/www/monero/node_modules/bignum/binding/bignum.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/monero/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
2016-08-31 21:42:02 [master] Pool fork 4 died, spawning replacement worker...

how to fix?

**Comment by stestaz** [comment]
I've removed node 10 and installed node 12 and now the error is

Error: Module version mismatch. Expected 14, got 47.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/monero/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
2016-08-31 21:49:26 [master] Pool fork 4 died, spawning replacement worker...

**Comment by mxjoe** [comment]
Try installing bignum: npm install bignum

This solved my problem.
