### ISSUE TITLE
Error: Failed to parse block

### ISSUE THREAD

**Issue by skygong** [zone117x/node-cryptonote-pool#110]
Error: Failed to parse block
    at Object.BlockTemplate.nextBlob (/home/ubuntu/pool/lib/pool.js:128:23)
    at Object.Miner.getJob (/home/ubuntu/pool/lib/pool.js:301:41)
    at handleMinerMethod (/home/ubuntu/pool/lib/pool.js:510:28)
    at handleMessage (/home/ubuntu/pool/lib/pool.js:644:13)
    at Socket.socket.on.on.on.pushMessage (/home/ubuntu/pool/lib/pool.js:698:25)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)

**Comment by bladedoyle** [comment]
Whats the fix?

2017-01-10 18:37:44 [master] Pool fork 1 died, spawning replacement worker...
2017-01-10 18:37:46 [unlocker] No blocks candidates in redis
2017-01-10 18:37:53 [api] Stat collection finished: 3 ms redis, 9498 ms daemon
2017-01-10 18:37:53 [api] Broadcasting to 2 visitors and 0 address lookups
2017-01-10 18:37:53 [pool] (Thread 1) New block to mine at height 1220519 w/ difficulty of 6140966093
2017-01-10 18:37:53 [pool] (Thread 1) Started server listening on port 3333

Error: Failed to parse block
    at Object.BlockTemplate.nextBlob (/pool/lib/pool.js:128:23)
    at Object.Miner.getJob (/pool/lib/pool.js:301:41)
    at handleMinerMethod (/pool/lib/pool.js:510:28)
    at handleMessage (/pool/lib/pool.js:644:13)
    at Socket.socket.on.on.on.pushMessage (/pool/lib/pool.js:698:25)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)

**Comment by jasonridesabike** [comment]
I'm getting the same error, thinking it's related to the hardfork. I'm going to rebuild and resync my node and see if that helps.

**Comment by mastercake10** [comment]
same.
Error: Failed to parse block
    at Object.BlockTemplate.nextBlob (/root/linus/monero/pool/lib/pool.js:129:23)
    at Object.Miner.getJob (/root/linus/monero/pool/lib/pool.js:302:41)
    at handleMinerMethod (/root/linus/monero/pool/lib/pool.js:511:28)
    at handleMessage (/root/linus/monero/pool/lib/pool.js:645:13)
    at Socket.socket.on.on.on.pushMessage (/root/linus/monero/pool/lib/pool.js:699:25)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)

**Comment by nibbons** [comment]
Does anyone have experience patching this for other CryptoNote coins besides Monero?  I am getting this same error but with DigitalNote...any advice on how to approach a fix (what to focus on etc) would be greatly appreciated.  My error here: https://i.imgur.com/5vh9yQK.jpg I was told this may be because of merged mining support added but I do not know.

**Comment by d3ancole1995** [comment]
Same issue. Anybody have a fix for it?

**Comment by MattTwinkleToes** [comment]
Yeah, naturally this has me concerned as I am unable to access my Monero coins.  IT was all working fine, restarted my laptop and now this.

```
2017-09-18 23:08:33.406	    7f7256275740	ERROR	cn	src/cryptonote_basic/cryptonote_format_utils.cpp:102	Failed to parse transaction from blob
2017-09-18 23:08:33.406	    7f7256275740	ERROR	txpool	src/cryptonote_core/tx_pool.cpp:1020	Failed to parse tx from txpool
2017-09-18 23:08:33.406	    7f7256275740	ERROR	cn	src/cryptonote_core/cryptonote_core.cpp:409	Failed to initialize memory pool
```

**Comment by bladedoyle** [comment]
I think there was a hard fork a few days ago.  probably need updates related to that?

**Comment by MattTwinkleToes** [comment]
I just installed it today
