### ISSUE TITLE
[master] Block unlocker died, spawning replacement...

### ISSUE THREAD

**Issue by skygong** [zone117x/node-cryptonote-pool#111]
Error: Object true has no method 'map'
    at async.waterfall.orphanCommands (/home/sky/newbbr/lib/blockUnlocker.js:100:40)
    at nextTask (/home/sky/newbbr/node_modules/async/dist/async.js:5021:18)
    at /home/sky/newbbr/node_modules/async/dist/async.js:5015:17
    at /home/sky/newbbr/node_modules/async/dist/async.js:339:31
    at /home/sky/newbbr/node_modules/async/dist/async.js:847:20
    at /home/sky/newbbr/lib/blockUnlocker.js:92:17
    at /home/sky/newbbr/node_modules/async/dist/async.js:486:20
    at /home/sky/newbbr/node_modules/async/dist/async.js:3306:17
    at /home/sky/newbbr/node_modules/async/dist/async.js:952:25
    at iteratorCallback (/home/sky/newbbr/node_modules/async/dist/async.js:995:17)

2016-09-13 15:36:19 [master] Block unlocker died, spawning replacement...

**Comment by wasiflaeeq** [comment]
were you able to find the solution for this? I am facing same issue... Found monero block and now have no clue  :D
