### ISSUE TITLE
npm update fails

### ISSUE THREAD

**Issue by seb432** [zone117x/node-cryptonote-pool#113]
Hi,
While installing the "npm update" fails on a Centos  7.2.1511 on multi-hashing and cryptone-util :

 
make: *** [Release/obj.target/cryptonote/src/main.o] Error 1
make: Leaving directory `/home/webadmin/Pool/pool/node_modules/cryptonote-util/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-327.28.3.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/webadmin/Pool/pool/node_modules/cryptonote-util
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

make: *** [Release/obj.target/multihashing/multihashing.o] Error 1
make: Leaving directory `/home/webadmin/Pool/pool/node_modules/multi-hashing/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-327.28.3.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/webadmin/Pool/pool/node_modules/multi-hashing
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Linux 3.10.0-327.28.3.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

**Comment by gaffelosked** [comment]
I've got the same issue, please help.

**Comment by loopyman** [comment]
You're using  incorrect versions:
npm ERR! node v4.5.0
npm ERR! npm v2.15.9

I use node version 0.10.48 with much success. I believe any 0.10.X version should work.
I also use the Node Version Manager to install / select / test various node versions. 

https://www.digitalocean.com/community/tutorials/how-to-install-node-js-with-nvm-node-version-manager-on-a-vps

Or you can always build  from source.
