### ISSUE TITLE
Unlocker module crash.

### ISSUE THREAD

**Issue by monerol** [zone117x/node-cryptonote-pool#116]
After 1st block i can see the unlocker module crash:

```
TypeError: Cannot read property 'length' of null
    at /home/monerol/pool/lib/blockUnlocker.js:69:35
    at /home/monerol/pool/node_modules/async/dist/async.js:486:20
    at /home/monerol/pool/node_modules/async/dist/async.js:3308:17
    at /home/monerol/pool/node_modules/async/dist/async.js:952:25
    at iteratorCallback (/home/monerol/pool/node_modules/async/dist/async.js:997:17)
    at /home/monerol/pool/node_modules/async/dist/async.js:847:20
    at /home/monerol/pool/node_modules/async/dist/async.js:3301:21
    at /home/monerol/pool/lib/blockUnlocker.js:65:21
    at /home/monerol/pool/lib/apiInterfaces.js:56:9
    at IncomingMessage.<anonymous> (/home/monerol/pool/lib/apiInterfaces.js:32:13)
```

**Followed by**

```
TypeError: Object true has no method 'map'
    at async.waterfall.orphanCommands (/home/monerol/pool/lib/blockUnlocker.js:82:40)
    at nextTask (/home/monerol/pool/node_modules/async/dist/async.js:5021:18)
    at /home/monerol/pool/node_modules/async/dist/async.js:5015:17
    at /home/monerol/pool/node_modules/async/dist/async.js:339:31
    at /home/monerol/pool/node_modules/async/dist/async.js:847:20
    at /home/monerol/pool/lib/blockUnlocker.js:75:17
    at /home/monerol/pool/node_modules/async/dist/async.js:486:20
    at /home/monerol/pool/node_modules/async/dist/async.js:3306:17
    at /home/monerol/pool/node_modules/async/dist/async.js:952:25
    at iteratorCallback (/home/monerol/pool/node_modules/async/dist/async.js:995:17)
```

**Comment by zone117x** [comment]
@clintar actually fix this in his branch by pinning the async npm package to 1.x. I've just committed a similar change here which should fix this issue https://github.com/zone117x/node-cryptonote-pool/commit/f1622050e059b57e2c648970155ff28ff9077f1c
Please test and let me know.

**Comment by seb432** [comment]
Had the same problem.

unlocker_info.log says  at start -> Unlocked 2 blocks and update balances for 42 workers

It seems to fixe however miner balance keep at 0.00000000000 ??

**Comment by monerol** [comment]
Found 1 block before fix, miners balance keep at 0 and i have **No blocks candidates** in redis message when start unlocker after fix.

**Comment by monerol** [comment]
In admin panel i can see:
Total Owed
    0.000000000000
Total Paid
    0.000000000000
Total Mined
    10.553800000000

**Comment by seb432** [comment]
Confirmed. Same problem here (redis 2.6). The fix is not enough.

workers balance are not  updated when block is unlocked.

**Comment by clintar** [comment]
Hmm, I'll try to get pool running on testnet and try to reproduce this with latest monero release

**Comment by seb432** [comment]
Monero node is not the very latest on my end

**Comment by monerol** [comment]
I have the latest monero binaries.

**Comment by seb432** [comment]
Any update ? It's a very frustrating situation for workers.

**Comment by zone117x** [comment]
I'm not in a position to help debug this issue. @clintar and other pool ops are you best resource for this. Trying talking with them in #monero-pools and see what submodule versions they are using.

**Comment by bladedoyle** [comment]
Same issue.  Block found, but nothing in my wallet.  

==> unlocker_crash.log <==
2016-10-02 17:14:36
TypeError: Object true has no method 'map'

Any way to recover my block?

**Comment by clintar** [comment]
See if you can set cryptonote-util in package.json to

"cryptonote-util": "git://github.com/clintar/node-cryptonote-util.git#xmr-Nan-2.0"
and get it to work.

**Comment by clintar** [comment]
oh yeah, and npm update after that

**Comment by monerol** [comment]
Played with node and async versions and cloned @clintar repo, now it is working, both unlocker and payments, can check at [monerol.com](http://monerol.com)

**Comment by gaffelosked** [comment]
Thanks for the heads up, not going to be wasting any time on this. Other open-source pools ftw!

**Comment by blackice2013** [comment]
Anyone update on this.
Having same problem here and no idea how to fix it...

**Comment by paracelsox** [comment]
I can make manual payments without problems,But the automatic payment for the workers does not come out....Please someone with an idea so you can handle it?

Balance after wallet ( admin pool )

{"available_balance":4836147990662,"locked_amount":0}

Payments log..

2017-10-19 23:31:14 No workers' balances reached the minimum payment threshold2017-10-19 23:32:14 No workers' balances reached the minimum payment threshold2017-10-19 23:33:14 No workers' balances reached the minimum payment threshold2017-10-19 23:34:14 No workers' balances reached the minimum payment threshold2017-10-19 23:35:14 No workers' balances reached the minimum payment threshold2017-10-19 23:36:14 No workers' balances reached the minimum payment threshold2017-10-19 23:37:14 No workers' balances reached the minimum payment threshold


Please help............
--
