### ISSUE TITLE
ERROR doing node init.js

### ISSUE THREAD

**Issue by blackice2013** [zone117x/node-cryptonote-pool#129]
I've been runing this few days ago without any problem, but now I suddenly get this error:

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pool/pool/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

What con It be? I didnt changed anything!! :/
Please Help

**Comment by Dormage** [comment]
Same issue. The error can happen if the modules loaded are for a different architecture.
I rebuilt the node_modules after reinstalling npm but it did not help.
