### ISSUE TITLE
Error with binding files

### ISSUE THREAD

**Issue by mastercake10** [zone117x/node-cryptonote-pool#131]
Hello,
I installed the pool today, but when I run it I got the following error:

> 2016-12-18 23:28:19 [master] Pool fork 1 died, spawning replacement worker...
2016-12-18 23:28:21 [api] Stat collection finished: 4 ms redis, 5 ms daemon
2016-12-18 23:28:21 [api] Broadcasting to 3 visitors and 1 address lookups
/home/linus/monero/pool/node_modules/bindings/bindings.js:91
  throw err
  ^
Error: Could not locate the bindings file. Tried:
 → /home/linus/monero/pool/node_modules/multi-hashing/build/multihashing.node
 → /home/linus/monero/pool/node_modules/multi-hashing/build/Debug/multihashing.node
 → /home/linus/monero/pool/node_modules/multi-hashing/build/Release/multihashing.node
 → /home/linus/monero/pool/node_modules/multi-hashing/out/Debug/multihashing.node
 → /home/linus/monero/pool/node_modules/multi-hashing/Debug/multihashing.node
 → /home/linus/monero/pool/node_modules/multi-hashing/out/Release/multihashing.node
 → /home/linus/monero/pool/node_modules/multi-hashing/Release/multihashing.node
 → /home/linus/monero/pool/node_modules/multi-hashing/build/default/multihashing.node
 → /home/linus/monero/pool/node_modules/multi-hashing/compiled/6.9.2/linux/x64/multihashing.node
    at bindings (/home/linus/monero/pool/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/linus/monero/pool/node_modules/multi-hashing/index.js:1:99)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/linus/monero/pool/lib/pool.js:7:20)

Versions:

**node -v
v6.9.2
npm -v
3.10.9
Debian GNU/Linux 8.5 (jessie)**

I tried to start the pool with different node versions, like 0.11 but that didn't help.
Is there something wrong with the multi-hashing module?

I also got a error on npm install:

`
make: *** [Release/obj.target/cryptonote/src/main.o] Error 1
make: Leaving directory '/home/linus/monero/pool/node_modules/cryptonote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/linus/monero/pool/node_modules/cryptonote-util
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! cryptonote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptonote-util@0.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonote-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/linus/monero/pool/npm-debug.log
`

**Comment by mastercake10** [comment]
Fixed it myself:

cryptonote-util requires an older version, v0.12.5 worked for me.
nvm install 0.12.5
npm install bignum
