### ISSUE TITLE
Error: Failed to parse block 

### ISSUE THREAD

**Issue by ub14** [zone117x/node-cryptonote-pool#151]
Tuned coin bytecoin. When the miner is turned on, the error "Error: Failed to parse block" appears.

Once it was possible to begin to extract a coin for a minute, after the restart of the miner again such an error went.

Bytecoind and sipmlewallet updated. All the default settings, added only sipmlewallet (--rpc-bind-port 8082 --daemon-port 8081)

Tell me, what's the problem? I beat the fifth day, I can not find an error.

> 2017-03-17 01:29:44 [payments] No workers' balances reached the minimum payment threshold
> 2017-03-17 01:29:53 [api] Stat collection finished: 27 ms redis, 9004 ms daemon
> 2017-03-17 01:29:53 [api] Broadcasting to 0 visitors and 0 address lookups
> 2017-03-17 01:29:55 [pool] (Thread 1) New block to mine at height 1222720 w/ difficulty of 46961927
> 2017-03-17 01:29:55 [pool] (Thread 1) Started server listening on port 5555
> 2017-03-17 01:30:12 [pool] (Thread 2) New block to mine at height 1222720 w/ difficulty of 46961927
> 2017-03-17 01:30:12 [pool] (Thread 2) Started server listening on port 5555
> 2017-03-17 01:30:14 [unlocker] No blocks candidates in redis
> 
> Error: Failed to parse block
>     at Object.BlockTemplate.nextBlob (/home/ub14/poolx/lib/pool.js:128:23)
>     at Object.Miner.getJob (/home/ub14/poolx/lib/pool.js:301:41)`
>     at handleMinerMethod (/home/ub14/poolx/lib/pool.js:510:28)
>     at handleMessage (/home/ub14/poolx/lib/pool.js:644:13)
>     at Socket.socket.on.on.on.pushMessage (/home/ub14/poolx/lib/pool.js:698:25)
>     at Socket.EventEmitter.emit (events.js:95:17)
>     at Socket.<anonymous> (_stream_readable.js:746:14)
>     at Socket.EventEmitter.emit (events.js:92:17)
>     at emitReadable_ (_stream_readable.js:408:10)
>     at emitReadable (_stream_readable.js:404:5)
> 
> 2017-03-17 01:30:37 [master] Pool fork 2 died, spawning replacement worker...
> 2017-03-17 01:30:42 [pool] (Thread 1) New block to mine at height 1222721 w/ difficulty of 47045153
> 2017-03-17 01:30:42 [api] Stat collection finished: 6 ms redis, 43443 ms daemon
> 2017-03-17 01:30:42 [api] Broadcasting to 0 visitors and 0 address lookups
> 2017-03-17 01:30:44 [unlocker] No blocks candidates in redis

**Comment by ub14** [comment]
В общем, напишу по-русски - переводите.

Эта ошибка связана с bytecoind. Для Windows она старая, её нужно самому скомпилировать из исходников. Версия 2.0.1.1221 - очень медленнее, продолжает работать, если прервалось с ошибкой.

А теперь самое главное. Если bytecoind у Вас повис во время работы и Ctrl+C не даёт завершиться самостоятельно или Вы принудительно закрыли bytecoind. То при запуске возможно у Вас посыпятся ошибки как в заголовке темы. Так, что если начнёте качать заново blockchain, то останавливайте и делайте копию. У меня на 500000 блоков была ручная остановка (Ctrl+C) и выгрузка заняла более 30 минут (Xeon e3-1220, 16Gb, 2Tb HDD raid mirror). bytecoind работает с одним ядром.

При новом запуске, создал новый кошелёк, сделал его копию тоже (чистую), останавливать его не пробывал.

**Comment by ub14** [comment]
на 530000 опять появилась эта ошибка. Остановил bytecoind и начал с сохранённой 500000. Позже отпишу.

**Comment by ub14** [comment]
Ладно, поехали, будем ставить эксперимент. Найдём ошибку или как обходить глюки.
bytecoind и simplewallet (Windows) - 2.0.1.1221. Node (Ubuntu 14)

Запущен кошелёк BytecoinWallet 1.1.1 (Windows Server 2012 R2). bytecoind принудительно с ним синхронизируется. При жёстком завершении backup blockchain-500000 на 507000 кнопками Ctrl+C, вышла ошибка ... и bytecoind завис. CMD был закрыт принудительно. После запуска blockchsin 507000, началось восстановление индекса, после восстановления ошибок при майнинге не возникло, что странно.

Сначало останавливается Node. Далее - завершение bytecoind происходит команде Exit (не кнопками Ctrl+C). Simplewallet не трогается.

1. Произвёл остановку bytecoind на blockchain-534700, сделал копию, продолжил, ошибок не обнаружено.
