### ISSUE TITLE
Connecting a miner to the pool crashes the pool

### ISSUE THREAD

**Issue by hinch** [zone117x/node-cryptonote-pool#152]
Based off latest git revision pull when running the pool and connecting a miner causes the pool fork to crash and restart.

Perhaps important to this may be instead of using your version of bignum I've changed to using snipa's bignum from his repository as his built without errors yours wouldn't build using npm update. simply changed the url in the json.  
Everything else seems to work fine.

TypeError: buffArray.reverse is not a function
    at Miner.getTargetHex (/home/poolhome/pool/lib/pool.js:286:19)
    at Miner.getJob (/home/poolhome/pool/lib/pool.js:303:27)
    at handleMinerMethod (/home/poolhome/pool/lib/pool.js:510:28)
    at handleMessage (/home/poolhome/pool/lib/pool.js:644:13)
    at Socket.<anonymous> (/home/poolhome/pool/lib/pool.js:698:25)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:563:20)

(node:14767) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
2017-03-17 10:25:26 [api] Stat collection finished: 2 ms redis, 87 ms daemon
2017-03-17 10:25:26 [api] Broadcasting to 3 visitors and 0 address lookups
2017-03-17 10:25:26 [master] Pool fork 2 died, spawning replacement worker...

**Comment by xiego** [comment]
Same issue as here:
https://github.com/zone117x/node-cryptonote-pool/issues/93#issuecomment-157628147

Hope this helps

**Comment by xiego** [comment]
https://github.com/zone117x/node-cryptonote-pool/issues/93#issuecomment-157628147

I fixed this issue with this solution.

**Comment by nibbons** [comment]
@xiego can you please advise me/help me out with with a little more detail?  I finally got the VPS end all up and running but when I try to connect with a miner the pool dies:

```
Error: Failed to parse block
    at Object.BlockTemplate.nextBlob (/root/cryptonote-universal-pool/lib/pool.js:122:23)
    at Object.Miner.getJob (/root/cryptonote-universal-pool/lib/pool.js:299:41)
    at handleMinerMethod (/root/cryptonote-universal-pool/lib/pool.js:494:28)
    at handleMessage (/root/cryptonote-universal-pool/lib/pool.js:624:13)
    at Socket.socket.on.on.on.pushMessage (/root/cryptonote-universal-pool/lib/pool.js:678:25)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)

2017-06-06 04:16:37 [master] Pool fork 1 died, spawning replacement worker...
```

My miner gives error: "stratum_recv_line failed".  Did you change the pool code?

**Comment by mohahn** [comment]
Same behaviour here

**Comment by dinho-afsn** [comment]
try 
Replace in your package.json
"cryptonote-util": "git://github.com/forknote/node-cryptonote-util.git"

Remove the folder node_modules or the module to be replaced
And run npm update again

**Comment by docgramps** [comment]
@dinho-afsn Thank you!  That solved the issue for me.
