### ISSUE TITLE
npm update failed ??

### ISSUE THREAD

**Issue by napoleon2121** [zone117x/node-cryptonote-pool#156]
make: *** [Release/obj.target/cryptonote/src/main.o] Error 1
make: Leaving directory '/home/napoleon/cryptonote/node_modules/cryptonote-util/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.8.0-46-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/napoleon/cryptonote/node_modules/cryptonote-util
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
cryptonote-universal-pool@0.0.1 /home/napoleon/cryptonote
├── async@2.3.0
├── base58-native@0.1.4
├── bignum@0.12.5
├── cli-color@1.2.0
├── dateformat@2.0.0
├── multi-hashing@0.0.9  (git://github.com/fancoder/node-multi-hashing.git#ec00b7429b668b3366d80a8fa85e9c22b4792d70)
└── redis@2.7.1

npm ERR! Linux 4.8.0-46-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! cryptonote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonote-util@0.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonote-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/napoleon/cryptonote/npm-debug.log

**Comment by xiego** [comment]
This problem was addressed and solved a few below your own. Here.

https://github.com/zone117x/node-cryptonote-pool/issues/93#issuecomment-157628147

**Comment by napoleon2121** [comment]
yea that is correct. i didn't saw it or passed the issue. thanks allot for the help
