### ISSUE TITLE
Error when connecting a miner to the pool

### ISSUE THREAD

**Issue by waxxmaster** [zone117x/node-cryptonote-pool#157]
Everything seems to works but i got an error when i'm trying to connect a miner.
The miner disconnect immediately (Error: Read error from target [***.***.***.***:3333], error [asio.misc:2, End of file]) on the miner side.

And the error on the pool side is : 

Error: Failed to parse block
    at Error (native)
    at Object.nextBlob (/home/vincent_anselmo/pool/lib/pool.js:128:23)
    at Object.getJob (/home/vincent_anselmo/pool/lib/pool.js:301:41)
    at handleMinerMethod (/home/vincent_anselmo/pool/lib/pool.js:510:28)
    at handleMessage (/home/vincent_anselmo/pool/lib/pool.js:644:13)
    at Socket.<anonymous> (/home/vincent_anselmo/pool/lib/pool.js:698:25)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
2017-04-25 15:38:33 [master] Pool fork 1 died, spawning replacement worker...

I don't know where is the problem, i'm connected to a local monerod testnet node and monero-wallet-cli. It seems to retrieve the blocks correctly :
2017-04-25 15:38:47 [unlocker] No blocks candidates in redis 
2017-04-25 15:43:20 [pool] (Thread 1) New block to mine at height 897349 w/ difficulty of 26619

**Comment by falcron11468** [comment]
Same Problem
