### ISSUE TITLE
Erros on start

### ISSUE THREAD

**Issue by dinho-afsn** [zone117x/node-cryptonote-pool#171]
hi, how to solve this problem?

TypeError: Cannot read property 'pool' of undefined
    at /home/dinho/pool/lib/charts.js:148:30
    at IncomingMessage.<anonymous> (/home/dinho/pool/lib/apiInterfaces.js:31:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

2017-07-12 16:18:29 [master] chartsDataCollector died, spawning replacement...
2017-07-12 16:18:30 [api] Error getting daemon data {"code":"ECONNRESET"}
2017-07-12 16:18:30 [api] Stat collection finished: 36 ms redis, 60652 ms daemon
2017-07-12 16:18:30 [api] Error collecting all stats
2017-07-12 16:18:30 [pool] (Thread 1) Error polling getblocktemplate {"code":"ECONNRESET"}
2017-07-12 16:18:30 [pool] (Thread 4) Error polling getblocktemplate {"code":"ECONNRESET"}
2017-07-12 16:18:30 [pool] (Thread 1) Could not start pool
2017-07-12 16:18:30 [pool] (Thread 4) Could not start pool
2017-07-12 16:18:30 [pool] (Thread 3) Error polling getblocktemplate {"code":"ECONNRESET"}
2017-07-12 16:18:30 [pool] (Thread 3) Could not start pool
2017-07-12 16:18:30 [pool] (Thread 2) Error polling getblocktemplate {"code":"ECONNRESET"}
2017-07-12 16:18:30 [pool] (Thread 2) Could not start pool
2017-07-12 16:18:31 [charts] Started

tanks

**Comment by coinsinternet** [comment]
I  have the  same issue?
Did you get it resolved?
Thanks
