### ISSUE TITLE
node-gyp rebuild fails during npm update

### ISSUE THREAD

**Issue by AndyDurden** [zone117x/node-cryptonote-pool#178]
I have installed all the listed dependencies (plus node-gyp via 'npm install -g node-gyp').
I am able to compile monerod. (suggested in #137 )
I've tried to run 'npm update' using node versions 0.10.48, 0.12.18, and 0.4.8.4, all with similar results.
I also tried nibbons' solution in #117 : removing the ~/.node-gyp directory and then restarting before running npm update. Same issue.

Below is the output for node v0.10.48

```
cryptonote.target.mk:111: recipe for target 'Release/obj.target/cryptonote/src/crypto/crypto.o' failed
make: *** [Release/obj.target/cryptonote/src/crypto/crypto.o] Error 1
make: Leaving directory '/home/mon/pool/node_modules/cryptonote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/mon/.nvm/v0.10.48/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.9.0-3-amd64
gyp ERR! command "node" "/home/mon/.nvm/v0.10.48/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mon/pool/node_modules/cryptonote-util
gyp ERR! node -v v0.10.48
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 4.9.0-3-amd64
npm ERR! argv "/home/mon/.nvm/v0.10.48/bin/node" "/home/mon/.nvm/v0.10.48/bin/npm" "update"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! cryptonote-util@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptonote-util@0.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonote-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mon/pool/npm-debug.log
```

Here are a few lines surrounding the error in the npm-debug.log
```
902 info install cryptonote-util@0.0.3
903 verbose unsafe-perm in lifecycle true
904 info postinstall multi-hashing@0.0.9
905 verbose unlock done using /home/mon/.npm/_locks/multi-hashing-2cba70d825a6640f.lock for /home/mon/pool/node_modules/multi-hashing
906 verbose validateInstall loading /home/mon/pool/package.json for validation
**907 info cryptonote-util@0.0.3 Failed to exec install script**
908 verbose unlock done using /home/mon/.npm/_locks/cryptonote-util-774f2746dae7b643.lock for /home/mon/pool/node_modules/cryptonote-util
909 verbose stack Error: cryptonote-util@0.0.3 install: `node-gyp rebuild`
909 verbose stack Exit status 1
```

What's the deal here? Am I missing some unspecified dependencies?

**Comment by aaraya1516** [comment]
I'm having the same problem.
Ubuntu 17.04 x64
I've installed nodejs from the website, and from the repos. It's the same result.

**Comment by gene-telligent** [comment]
You're both using fairly new versions of your respective OSes -- Stretch and Zesty have quite a few new changes to their OS layout. Is it possible to use a previous version? I've managed to get it compiling and running on Debian Jessie (albeit with a few tweaks).

**Comment by rjcoupe** [comment]
Ubuntu Xenial, Node 6.11.2 (LTS):
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-1022-aws
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/node" "/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/pool/node_modules/multi-hashing
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
cryptonote-pool@0.0.1 /home/ubuntu/pool
└── cryptonote-util@0.0.3  (git://github.com/Snipa22/node-cryptonote-util.git#49d6ec72d499bba9144d4a3ebdf4b62a4262aa8a)

npm ERR! Linux 4.4.0-1022-aws
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/node" "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/npm" "update"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@0.0.9 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs multi-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/pool/npm-debug.log
```

**Comment by PhearZero** [comment]
Anyone who is having trouble, I just used NVM to set node to 0.10. So far Ubuntu x64 16.04 has no problems building. Make sure to remove your node_modules directory after you change node versions. So far only v0.10.* has been successful in building. We should put Travis-CI or Circle-CI on the repo with Code-Climate for static analysis

**Comment by StarSmasher44** [comment]
I still can't for the life of me get this to work, got the same issue.

**Comment by mxjoe** [comment]
With node v6.11.3 it isn't working under Ubuntu 16.04.3, too.

**Comment by mxjoe** [comment]
I found a solution, please see Post #93
