### ISSUE TITLE
Error connecting to pool - No data is displayed on the web -Can somebody help me? Thank you

### ISSUE THREAD

**Issue by escreativa** [zone117x/node-cryptonote-pool#182]
No data is displayed on the web - Link view web: 156.67.218.73
Inside the server I have created a pool and a cryptonote node
## My configuration data is:

**Node Cryptonote** - folder. /cryptonote/src   file: CryptoNoteConfig.h
[https://github.com/escreativa/cryptonote](https://github.com/escreativa/cryptonote)

const int      P2P_DEFAULT_PORT                              = 17236;
const int      RPC_DEFAULT_PORT                              = 18236;

const std::initializer_list<const char*> SEED_NODES = {
    "93.188.165.101:17236",
  "31.220.54.79:17236",
  "31.220.59.157:17236",
  "156.67.218.73:17236",
};

**Pool Cryptonote** - folder. /node-cryptonote/    file: config.json
[https://github.com/escreativa/node-cryptonote-pool](https://github.com/escreativa/node-cryptonote-pool)

    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 5,
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "secret-password"
    },

    "daemon": {
        "host": "0.0.0.0",
        "port": 17236
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 18236
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "auth": null
    }

**Pool Cryptonote** - folder. /var/www/html    file: config.js  - `Copied from website_example`

var api = "127.0.0.1:8117";

## Steps for starting the node and pool:

**step 1** Starting REDIS 
root@pool:  redis-server

**step 2** Starting NODE CRYPTONOTE 
root@pool:~/cryptonote/build/release/src # ./bytcoins --data-dir /root/blockchain
It tells me that the p2p and rpc ports are correct:
Net service binded on 0.0.0.0:17236
Starting core rpc server on address 127.0.0.1:18236

**step 3** Starting Nodejs - init.js
root@pool:~/node-cryptonote-pool#  node init.js

**step 4** Optional - Starting wallet - ./simplewallet
Then, if I want to, I open the wallet and it goes correctly

# ## My Error data is:

## **REDIS**

6195:M 09 Aug 17:48:16.195 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
6195:M 09 Aug 17:48:16.195 # Server initialized
6195:M 09 Aug 17:48:16.195 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
6195:M 09 Aug 17:48:16.196 * DB loaded from disk: 0.000 seconds
6195:M 09 Aug 17:48:16.196 * Ready to accept connections
6195:M 09 Aug 18:11:39.239 * 100 changes in 300 seconds. Saving...
6195:M 09 Aug 18:11:39.239 * Background saving started by pid 7429
7429:C 09 Aug 18:11:39.241 * DB saved on disk

## **CRYPTONOTE NODE**

root@pool-nodo:~/cryptonote/build/release/src# ./bytcoins --data-dir /root/blockchain
05:04:10.948436 INFO bytcoins v1.1.1.1()
05:04:10.948657 INFO Module folder: ./bytcoins
05:04:10.949911 INFO Initializing p2p server...
05:04:10.950088 INFO Binding on 0.0.0.0:17236
05:04:10.950168 INFO Net service binded on 0.0.0.0:17236
05:04:10.950216 INFO Attempting to add IGD port mapping.
05:04:14.953620 INFO No IGD was found.
05:04:14.953780 INFO P2p server initialized OK
05:04:14.953873 INFO Initializing core...
05:04:14.963101 INFO Loading blockchain...
05:04:14.963237 WARNING No actual blockchain cache found, rebuilding internal structures...
05:04:14.963297 INFO Height 0 of 2001
05:04:15.005371 INFO Height 1000 of 2001
05:04:15.045480 INFO Height 2000 of 2001
05:04:15.045599 INFO Rebuilding internal structures took: 0.0823055
05:04:15.045680 INFO Loading blockchain indices for BlockchainExplorer...
05:04:15.045757 WARNING No actual blockchain indices for BlockchainExplorer found, rebuilding...
05:04:15.045808 INFO Height 0 of 2001
05:04:15.079242 INFO Height 1000 of 2001
05:04:15.112417 INFO Height 2000 of 2001
05:04:15.112534 INFO Rebuilding blockchain indices took: 0.0667282
05:04:15.112795 INFO Blockchain initialized. last block: 2000, d0.h0.m10.s1 time ago, current difficulty: 9128
05:04:15.112854 INFO Core initialized OK
05:04:15.112979 INFO Starting core rpc server on address 127.0.0.1:18236
05:04:15.113075 INFO Core rpc server started ok
05:04:15.113124 INFO Starting p2p net loop...
05:04:15.113163 INFO Starting node_server
05:04:15.114123 INFO [31.220.59.157:33169 INC] Sync data returned unknown top block: 2000 -> 2007 [7 blocks (0 days) behind] 
05:04:15.114123 INFO SYNCHRONIZATION started
05:04:16.156146 INFO [31.220.59.157:17236 OUT] Sync data returned unknown top block: 2000 -> 2007 [7 blocks (0 days) behind] 
05:04:16.156146 INFO SYNCHRONIZATION started
05:04:17.159280 INFO [31.220.54.79:17236 OUT] Sync data returned unknown top block: 2000 -> 2007 [7 blocks (0 days) behind] 
05:04:17.159280 INFO SYNCHRONIZATION started
05:04:18.078343 INFO [93.188.165.101:17236 OUT] Sync data returned unknown top block: 2000 -> 2007 [7 blocks (0 days) behind] 
05:04:18.078343 INFO SYNCHRONIZATION started
05:04:18.078599 INFO 
05:04:18.078599 INFO **********************************************************************
05:04:18.078599 INFO The daemon will start synchronizing with the network. It may take up to several hours.
05:04:18.078599 INFO 
05:04:18.078599 INFO You can set the level of process detailization* through "set_log <level>" command*, where <level> is between 0 (no details) and 4 (very verbose).
05:04:18.078599 INFO 
05:04:18.078599 INFO Use "help" command to see the list of available commands.
05:04:18.078599 INFO 
05:04:18.078599 INFO Note: in case you need to interrupt the process, use "exit" command. Otherwise, the current progress won't be saved.
05:04:18.078599 INFO **********************************************************************
05:04:21.906564 INFO [31.220.59.157:33169 INC] SYNCHRONIZED OK
05:04:21.906660 INFO 
05:04:21.906660 INFO **********************************************************************
05:04:21.906660 INFO You are now synchronized with the network. You may now start simplewallet.
05:04:21.906660 INFO 
05:04:21.906660 INFO Please note, that the blockchain will be saved only after you quit the daemon with "exit" command or if you use "save" command.
05:04:21.906660 INFO Otherwise, you will possibly need to synchronize the blockchain again.
05:04:21.906660 INFO 
05:04:21.906660 INFO Use "help" command to see the list of available commands.
05:04:21.906660 INFO **********************************************************************
05:04:42.159541 WARNING [127.0.0.1:59894 INC] Exception in connectionHandler: Levin signature mismatch
05:04:42.247694 WARNING [127.0.0.1:59898 INC] Exception in connectionHandler: Levin signature mismatch
05:04:42.300570 WARNING [127.0.0.1:59902 INC] Exception in connectionHandler: Levin signature mismatch
05:04:42.348814 WARNING [127.0.0.1:59906 INC] Exception in connectionHandler: Levin signature mismatch
05:04:43.166687 WARNING [127.0.0.1:59948 INC] Exception in connectionHandler: Levin signature mismatch
05:04:43.254745 WARNING [127.0.0.1:59958 INC] Exception in connectionHandler: Levin signature mismatch
05:04:43.356395 WARNING [127.0.0.1:59970 INC] Exception in connectionHandler: Levin signature mismatch
05:04:44.169590 WARNING [127.0.0.1:59994 INC] Exception in connectionHandler: Levin signature mismatch
05:04:44.256665 WARNING [127.0.0.1:59996 INC] Exception in connectionHandler: Levin signature mismatch
05:04:44.358893 WARNING [127.0.0.1:59998 INC] Exception in connectionHandler: Levin signature mismatch
05:04:44.776986 WARNING [127.0.0.1:60008 INC] Exception in connectionHandler: Levin signature mismatch
05:04:45.172277 WARNING [127.0.0.1:60022 INC] Exception in connectionHandler: Levin signature mismatch
05:04:45.259368 WARNING [127.0.0.1:60024 INC] Exception in connectionHandler: Levin signature mismatch
05:04:45.360683 WARNING [127.0.0.1:60028 INC] Exception in connectionHandler: Levin signature mismatch

## NODE CRYPTONOTE POOL - NODEJS

root@pool-nodo:~/node-cryptonote-pool# node init.js
2017-08-10 05:08:02 [master] Pool spawned on 3 thread(s)
2017-08-10 05:08:03 [unlocker] Started
2017-08-10 05:08:03 [payments] Started
2017-08-10 05:08:03 [unlocker] No blocks candidates in redis
2017-08-10 05:08:03 [payments] No workers' balances reached the minimum payment threshold

Error: bind EADDRINUSE null:8117
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at listenOnMasterHandle (net.js:1399:16)
    at rr (internal/cluster/child.js:111:12)
    at Worker.send (internal/cluster/child.js:78:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)

2017-08-10 05:08:03 [master] API died, spawning replacement...

2017-08-10 05:08:06 [master] API died, spawning replacement...
(node:1137) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:1137) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:1143) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:1148) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

Thanks for helping me and using your time.
We accept collaborations. info@pool.bytcoins.org
We thank you with bytcoins.

Bytcoins
Gonzalo Linares Amezcua
www.bytcoins.org
info@bytcoins.org
Granada - Spain

**Comment by escreativa** [comment]
Already improved some of the ip and ports. But he still gives me another mistake.


**My modifications are:**
Pool Cryptonote - folder. /node-cryptonote/ file: config.json

"daemon": {
    "host": "156.67.218.73",
    "port": 9998
},

"wallet": {
    "host": "156.67.218.73",
    "port": 8082
},

sudo ./bytcoins  --rpc-bind-ip 156.67.218.73 --rpc-bind-port 9998

**Comment by dinho-afsn** [comment]
try
sudo apt-get install libboost1.55-all-dev
if not work
try 
Setup

At this point you should have your VPS started, putty up and running and your logged in as root.

Update Ubuntu

apt-get update 
apt-get dist-upgrade

Setup SWAP

I am setting up a 4GB swap, which may be overkill but it’s the most common swap sized used in most guides so ill keep it at that.

dd if=/dev/zero of=/mnt/myswap.swap bs=1M count=4000
mkswap /mnt/myswap.swap
swapon /mnt/myswap.swap

Now let’s add it into fstab so it’ll activate at boot.

nano /etc/fstab
Add the following line at the end of the file.

/mnt/myswap.swap none swap sw 0 0
Ctrl+O to save, and Ctrl+X to exit the nano editor.

Now your swap is setup, you can modify the size in the future if you need more or less.

–Install Required Packages

apt-get install build-essential libtool autotools-dev autoconf pkg-config libssl-dev
apt-get install libboost-all-dev git npm nodejs nodejs-legacy libminiupnpc-dev redis-server
add-apt-repository ppa:bitcoin/bitcoin
apt-get update
apt-get install libdb4.8-dev libdb4.8++-dev
curl https://raw.githubusercontent.com/creationix/nvm/v0.16.1/install.sh | sh
source ~/.profile
nvm install 0.10.25
nvm use 0.10.25

I hope it helps
