### ISSUE TITLE
Boost/variant.hpp  Problem

### ISSUE THREAD

**Issue by noobishpool** [zone117x/node-cryptonote-pool#184]
I allways have the same error:

make: Entering directory `/root/pool/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
In file included from ../src/main.cc:8:0:
../src/cryptonote_core/cryptonote_basic.h:7:29: fatal error: boost/variant.hpp: No such file or directory
 #include <boost/variant.hpp>
                             ^
compilation terminated.
make: *** [Release/obj.target/cryptonote/src/main.o] Error 1
make: Leaving directory `/root/pool/node_modules/cryptonote-util/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 2.6.32-042stab123.9
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/pool/node_modules/cryptonote-util
gyp ERR! node -v v0.10.20
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0

Tried with Ubuntu differnt versions, even with Centos 7, dont know what to do, someone can help me please ?

**Comment by rjcoupe** [comment]
Have you installed Boost as per the instructions?

**Comment by codebling** [comment]
It looks like this dep comes from [Snipa22/node-cryptonote-util](https://github.com/Snipa22/node-cryptonote-util/tree/xmr-Nan-2.0). This is a C module with some weak node-gyp bindings and could probably be refactored to use a more native node solution, like [boost-lib](https://www.npmjs.com/package/boost-lib).
