### ISSUE TITLE
Errror when build

### ISSUE THREAD

**Issue by xmrminer2017** [zone117x/node-cryptonote-pool#191]
4) Start the pool

node init.js

and get this errror

2017-08-27 14:41:41 [master] Pool fork 4 died, spawning replacement worker...
module.js:491
    throw err;
    ^

Error: Cannot find module '/root/monero/monero-v0.10.3.1/pool/node_modules/bignum/binding/bignum.node'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/monero/monero-v0.10.3.1/pool/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
2017-08-27 14:41:42 [master] Pool fork 1 died, spawning replacement worker...
module.js:491
    throw err;
    ^

Error: Cannot find module '/root/monero/monero-v0.10.3.1/pool/node_modules/bignum/binding/bignum.node'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/monero/monero-v0.10.3.1/pool/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
2017-08-27 14:41:42 [master] Pool fork 2 died, spawning replacement worker...
module.js:491
    throw err;
    ^

Error: Cannot find module '/root/monero/monero-v0.10.3.1/pool/node_modules/bignum/binding/bignum.node'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/monero/monero-v0.10.3.1/pool/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

**Comment by dcwatson84** [comment]
I got this error due to compilation issues. What fixed it for me was to install node-package-manager and ensure I was compiling/executing with nodejs 0.10. After installation the execution command should look something like this:
npm exec 0.20 node init.js
