### ISSUE TITLE
Pool Module workers die

### ISSUE THREAD

**Issue by dcwatson84** [zone117x/node-cryptonote-pool#193]
When I start up the pool module, the workers die with the stacktrace below. The code seems to compile correctly (allbeit with warnings). Am I missing a library somewhere? Using Ubuntu 16 and nodejs v0.10.48 (npm v2.15.1).
 

Error: /home/dcwatson/Downloads/pool/pool/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: cn_slow_hash
 at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/dcwatson/Downloads/pool/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/dcwatson/Downloads/pool/pool/node_modules/cryptonote-util/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by isbkch** [comment]
Were you able to figure this out ?
