### ISSUE TITLE
pool build on ubuntu 14.04

### ISSUE THREAD

**Issue by zeus911** [zone117x/node-cryptonote-pool#195]
./cpuminer -a cryptonight -q -o stratum+tcp://47.95.34.156:40050 -u 1Uj9UxoAo6XMny12wdtMkSGLLfXdtCQ5965Az8UpPtotfFhU3gHjRzGbmPZPQhhY6ojYwY2uPRKtSNuJ2WgErUNvP61dPSS -p x

[2017-08-29 11:01:02] stratum_recv_line failed
[2017-08-29 11:01:02] ...retry after 10 seconds
[2017-08-29 11:01:12] stratum_recv_line failed
[2017-08-29 11:01:12] ...retry after 10 seconds
[2017-08-29 11:01:22] stratum_recv_line failed
[2017-08-29 11:01:22] ...retry after 10 seconds

pool show errror:

Error: Failed to parse block
    at Object.BlockTemplate.nextBlob (/root/pool2/lib/pool.js:120:23)
    at Object.Miner.getJob (/root/pool2/lib/pool.js:297:41)
    at handleMinerMethod (/root/pool2/lib/pool.js:492:28)
    at handleMessage (/root/pool2/lib/pool.js:606:13)
    at Socket.socket.on.on.on.pushMessage (/root/pool2/lib/pool.js:660:25)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)

**Comment by RavenHuginn** [comment]
the same problem
