### ISSUE TITLE
Enable SSL 

### ISSUE THREAD

**Issue by gcasas84** [zone117x/node-cryptonote-pool#203]
Hi, I try to use website over SSL, to do it I enabled SSL support of api, I edited (lib/api.js)

```
var http = require('https');

var options = {
  key: fs.readFileSync('/etc/cert/privkey.pem'),
  cert: fs.readFileSync('/etc/cert/fullchain.pem')
};
```

and "http.createServer"

`var server = http.createServer(options, function(request, response)`

Then, if I edit (var api) from (website/config.js) to work with (https) works fine...

But I have a problem, (chartsDataCollector) doesn't work, in console I see:

```
2017-09-11 12:47:13
TypeError: Cannot read property 'pool' of undefined
    at /root/pool/lib/charts.js:149:30
    at ClientRequest.<anonymous> (/root/pool/lib/apiInterfaces.js:39:9)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketOnEnd [as onend] (http.js:1631:9)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:458:13)

2017-09-11 12:47:13
TypeError: Cannot read property 'pool' of undefined
    at /root/pool/lib/charts.js:149:30
    at ClientRequest.<anonymous> (/root/pool/lib/apiInterfaces.js:39:9)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketCloseListener (http.js:1585:9)
    at Socket.emit (events.js:117:20)
    at TCP.close (net.js:466:12)

2017-09-11 12:47:13
TypeError: Cannot read property 'pool' of undefined
    at /root/pool/lib/charts.js:155:30
    at ClientRequest.<anonymous> (/root/pool/lib/apiInterfaces.js:39:9)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketOnEnd [as onend] (http.js:1631:9)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:458:13)

2017-09-11 12:47:13
TypeError: Cannot read property 'pool' of undefined
    at /root/pool/lib/charts.js:155:30
    at ClientRequest.<anonymous> (/root/pool/lib/apiInterfaces.js:39:9)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketCloseListener (http.js:1585:9)
    at Socket.emit (events.js:117:20)
    at TCP.close (net.js:466:12)`
```

Any suggestion? 

Thanks !

**Comment by gcasas84** [comment]
Solved, I updated config.json and leave original api.js

**Comment by neurans** [comment]
How did you update config.json?

**Comment by gcasas84** [comment]
Hi @neurans , take a look here (https://github.com/clintar/cryptonote-universal-pool) 
copy config.json extra api parameters and (lib/api.js).
