### ISSUE TITLE
Unable to build on CENTOS 7

### ISSUE THREAD

**Issue by havenswift-hosting** [zone117x/node-cryptonote-pool#206]
Unable to build via npm update and getting the following - please does anyone any idea what is missing as think all dependencies are installed ?

make: *** [Release/obj.target/multihashing/multihashing.o] Error 1
make: Leaving directory `/root/pool/node_modules/multi-hashing/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-693.2.2.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/pool/node_modules/multi-hashing
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multi-hashing@0.0.9 install script.

**Comment by Ogy** [comment]
too

**Comment by WeOggy** [comment]
Solved? i'm having the problem too :(

**Comment by gvsro** [comment]
What node version are you using?
