### ISSUE TITLE
Unable a buil in opensuse 42.3

### ISSUE THREAD

**Issue by Soyasi** [zone117x/node-cryptonote-pool#210]
3364 info lifecycle cryptonote-util@0.0.1~install: cryptonote-util@0.0.1
3365 verbose lifecycle cryptonote-util@0.0.1~install: unsafe-perm in lifecycle true
3366 verbose lifecycle cryptonote-util@0.0.1~install: PATH: /usr/lib64/node_modules/npm8/bin/node-gyp-bin:/home2/eriel/bin/pool/cryptonote-universal/node_modules/cryptonote-util/node_modules/.bin:/home2/eriel/bin/pool/cryptonote-universal/node_modules/.bin:/home2/eriel/.cargo/bin:/usr/lib64/mpi/gcc/openmpi/bin:/home2/eriel/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games
3367 verbose lifecycle cryptonote-util@0.0.1~install: CWD: /home2/eriel/bin/pool/cryptonote-universal/node_modules/cryptonote-util
3368 silly lifecycle cryptonote-util@0.0.1~install: Args: [ '-c', 'node-gyp rebuild' ]
3369 silly lifecycle cryptonote-util@0.0.1~install: Returned: code: 1  signal: null
3370 info lifecycle cryptonote-util@0.0.1~install: Failed to exec install script
3371 verbose unlock done using /home2/eriel/.npm/_locks/staging-699ca7b9174ce8a9.lock for /home2/eriel/bin/pool/cryptonote-universal/node_modules/.staging
3372 verbose stack Error: cryptonote-util@0.0.1 install: `node-gyp rebuild`
3372 verbose stack Exit status 1
3372 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm8/lib/utils/lifecycle.js:289:16)
3372 verbose stack     at emitTwo (events.js:125:13)
3372 verbose stack     at EventEmitter.emit (events.js:213:7)
3372 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm8/lib/utils/spawn.js:40:14)
3372 verbose stack     at emitTwo (events.js:125:13)
3372 verbose stack     at ChildProcess.emit (events.js:213:7)
3372 verbose stack     at maybeClose (internal/child_process.js:927:16)
3372 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
3373 verbose pkgid cryptonote-util@0.0.1
3374 verbose cwd /home2/eriel/bin/pool/cryptonote-universal
3375 verbose Linux 4.4.87-25-default
3376 verbose argv "/usr/bin/node8" "/usr/bin/npm-default" "update"
3377 verbose node v8.6.0
3378 verbose npm  v5.3.0
3379 error code ELIFECYCLE
3380 error errno 1
3381 error cryptonote-util@0.0.1 install: `node-gyp rebuild`
3381 error Exit status 1
3382 error Failed at the cryptonote-util@0.0.1 install script.
3382 error This is probably not a problem with npm. There is likely additional logging output above.
3383 verbose exit [ 1, true ]
[2017-10-10T11_12_25_746Z-debug.log](https://github.com/zone117x/node-cryptonote-pool/files/1371745/2017-10-10T11_12_25_746Z-debug.log)

**## Is there any known solution?**

**Comment by msilvoli** [comment]
Opensuse 42.3 kernel 4.4.87-18.29-default
Did you manage this error ? I'm running same into the problem. I installed other versions from the same distributions but still receiving the same error...
