### ISSUE TITLE
npm update error

### ISSUE THREAD

**Issue by Qurmo** [zone117x/node-cryptonote-pool#212]
I get the following error when I try to do the "npm update" command
multihashing.target.mk:143: recipe for target 'Release/obj.target/multihashing/multihashing.o' failed
make: *** [Release/obj.target/multihashing/multihashing.o] Error 1
make: Leaving directory '/home/qurmo/pool/node_modules/multi-hashing/build'
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack at emitTwo (events.js:125:13)
gyp ERR! stack at ChildProcess.emit (events.js:213:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-97-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/qurmo/pool/node_modules/multi-hashing
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multi-hashing@0.0.9 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multi-hashing@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I've went so far back I actually formated my Linux Server, reinstalled everything from scratch but all remains the same.... Help :p

**Comment by mk148a** [comment]
mee to same problem, what's your linux version and everythink upgraded latest?

**Comment by mk148a** [comment]
I handle it, you install node v0.12.7 and remove node_modules directory and npm install

**Comment by msilvoli** [comment]
Same problem with OpenSUSE 42.3 and no solution 'til now...

**Comment by msilvoli** [comment]
My problem was solved with v0.10.48 
Case closed.
