### ISSUE TITLE
Api died

### ISSUE THREAD

**Issue by PowDex** [zone117x/node-cryptonote-pool#234]
Dispatch when me run init.js

> 2017-12-08 04:01:45 [master] Pool spawned on 2 thread(s)
> 2017-12-08 04:01:45 [unlocker] Started
> 2017-12-08 04:01:45 [unlocker] No blocks candidates in redis
> 2017-12-08 04:01:45 [payments] Started
> 2017-12-08 04:01:45 [payments] No workers' balances reached the minimum payment threshold
> 
> Error: bind EADDRINUSE
>     at errnoException (net.js:901:11)
>     at net.js:1081:30
>     at Object.3:1 (cluster.js:592:5)
>     at handleResponse (cluster.js:171:41)
>     at respond (cluster.js:192:5)
>     at handleMessage (cluster.js:202:5)
>     at process.EventEmitter.emit (events.js:117:20)
>     at handleMessage (child_process.js:318:10)
>     at child_process.js:392:7
>     at process.handleConversion.net.Native.got (child_process.js:91:7)
> 
> 2017-12-08 04:01:45 [master] API died, spawning replacement...
> 
> Error: bind EADDRINUSE
>     at errnoException (net.js:901:11)
>     at net.js:1081:30
>     at Object.6:1 (cluster.js:592:5)
>     at handleResponse (cluster.js:171:41)
>     at respond (cluster.js:192:5)
>     at handleMessage (cluster.js:202:5)
>     at process.EventEmitter.emit (events.js:117:20)
>     at handleMessage (child_process.js:318:10)
>     at child_process.js:392:7
>     at process.handleConversion.net.Native.got (child_process.js:91:7)
>

**Comment by frankdejonge** [comment]
@PowDex you get this error when something else is already bound to that port.

**Comment by m3nt0l** [comment]
Maybe you use same port on API SSLPort and API Port

**Comment by wennicky** [comment]
hi
same error here, do you mean https and http port?
what is the solution? modification in config file?

thanks

**Comment by antstalepresh** [comment]
In my case, I got error when run with `forever` and run with `node` again! :)

**Comment by Gokuref** [comment]
Which ports would it be? Someone knows?

[pool] (Thread 3) New block to mine at height 18 w/ difficulty of 85
Error: bind EADDRINUSE
    at errnoException (net.js:901:11)
    at net.js:1081:30
    at Object.5:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at child_process.js:392:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)

**Comment by Jiankun-Huang** [comment]
run  `sudo pkill -9 -f node` Then run` node init.js` and solved.
