### ISSUE TITLE
2017-12-20 09:57:09 [master] Redis version check failed

### ISSUE THREAD

**Issue by mpr555** [zone117x/node-cryptonote-pool#249]
When i try to run node init.js I get the above issue.
`Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/root/pool/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/root/pool/node_modules/redis/index.js:106:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)`

i have checked and it seems that the redis-server service is running.  running the redis-cli command also gets this
`Could not connect to Redis at 127.0.0.1:6379: Connection refused`

many thanks in advance

**Comment by wonchoe** [comment]
https://stackoverflow.com/questions/19091087/open-redis-port-for-remote-connections
