### ISSUE TITLE
error config is not defined

### ISSUE THREAD

**Issue by rvrsh3ll** [zone117x/node-cryptonote-pool#258]
Issues running "node init.js" tried specifying -config=config.json

node init.js
Failed to read config file config.json

SyntaxError: Unexpected token / in JSON at position 0
/home/pooluser/node-cryptonote-pool/lib/logger.js:16
var logDir = config.logging.files.directory;
                                 ^

ReferenceError: config is not defined
    at Object.<anonymous> (/home/pooluser/node-cryptonote-pool/lib/logger.js:16:34)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pooluser/node-cryptonote-pool/init.js:10:1)
    at Module._compile (module.js:570:32)

**Comment by rvrsh3ll** [comment]
P.S. my config is in the same directory

**Comment by Gokuref** [comment]
Hi, rvrsh3ll!  May I ask how did you fix it? ;)

**Comment by milaas** [comment]
I got the same error somebody have fix idea
thx

**Comment by stratm0s** [comment]
I'm having the same issue. Has anyone found a fix yet?

**Comment by developer60-stack** [comment]
any fix?
