### ISSUE TITLE
NPM Update

### ISSUE THREAD

**Issue by Qurmo** [zone117x/node-cryptonote-pool#270]
I get the following error when I execute "npm update"

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-104-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pooldaemon/pool/node_modules/multi-hashing
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
cryptonote-pool@0.0.1 /home/pooldaemon/pool
└── cryptonote-util@0.0.3  (git://github.com/Snipa22/node-cryptonote-util.git#49d6ec72d499bba9144d4a3ebdf4b62a4262aa8a)

npm ERR! Linux 4.4.0-104-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multi-hashing@0.0.9 install script 'node-gyp rebuild'.

**Comment by hoddy** [comment]
try this:
`nvm install 0.10.29`
`nvm use 0.10.29`
`npm install -g npm@1.3.10`
`npm update`
Basically just downgrades your nvm and npm versions.
