### ISSUE TITLE
Error: bind EADDRINUSE

### ISSUE THREAD

**Issue by jensej** [zone117x/node-cryptonote-pool#272]
Hello
I have error like below but I read that mean port is used But I checked it and reboot server and still this same error:

```
Error: bind EADDRINUSE
    at errnoException (net.js:901:11)
    at net.js:1081:30
    at Object.36:3 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at child_process.js:392:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
```

**Comment by NICKVALENTINO** [comment]
What was your solution?  I'm having the same issue, but only with 1 particular coin.  I've tried rebooting and even changing the coin's RPC & TCP ports.  Nothing's worked, so far.
