### ISSUE TITLE
node init.js error help 

### ISSUE THREAD

**Issue by lxmolo** [zone117x/node-cryptonote-pool#273]
I changed file package.json as below: 
from:
"multi-hashing": "git://github.com/zone117x/node-multi-hashing.git",
 "cryptonote-util": "git://github.com/LucasJones/node-cryptonote-util.git"

to:
"multi-hashing": "git://github.com/zone117x/node-multi-hashing.git",
 "cryptonote-util": "git://github.com/Snipa22/node-cryptonote-util#xmr-Nan-2.0"

npm update  is ok
but I run node init.js -config=config.json, error happened as below;
/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:88
        throw e
              ^
Error: /usr/local/pool/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: _ZN5boost6system15system_categoryEv
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/pool/node_modules/cryptonote-util/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
2018-01-22 02:07:07 [master] Pool fork 2 died, spawning replacement worker...

/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:88
        throw e
              ^
Error: /usr/local/pool/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: _ZN5boost6system15system_categoryEv
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/pool/node_modules/cryptonote-util/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
2018-01-22 02:07:07 [master] Pool fork 6 died, spawning replacement worker...

/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:88
        throw e
              ^
Error: /usr/local/pool/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: _ZN5boost6system15system_categoryEv
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/pool/node_modules/cryptonote-util/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
2018-01-22 02:07:07 [master] Pool fork 7 died, spawning replacement worker...

/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:88
        throw e
              ^
Error: /usr/local/pool/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: _ZN5boost6system15system_categoryEv
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/pool/node_modules/cryptonote-util/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
2018-01-22 02:07:09 [master] Pool fork 4 died, spawning replacement worker...

/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:88
        throw e
              ^
Error: /usr/local/pool/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: _ZN5boost6system15system_categoryEv
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/pool/node_modules/cryptonote-util/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
2018-01-22 02:07:09 [master] Pool fork 1 died, spawning replacement worker...
2018-01-22 02:07:09 [api] Error getting daemon data {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2018-01-22 02:07:09 [api] Stat collection finished: 0 ms redis, 0 ms daemon
2018-01-22 02:07:09 [api] Error collecting all stats
2018-01-22 02:07:09 [unlocker] No blocks candidates in redis

/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:88
        throw e
     /usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:88
         ^
        throw e
              ^
Error: /usr/local/pool/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: _ZN5boost6system15system_categoryEv
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/pool/node_modules/cryptonote-util/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Error: /usr/local/pool/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: _ZN5boost6system15system_categoryEv
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/pool/node_modules/cryptonote-util/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
2018-01-22 02:07:09 [master] Pool fork 3 died, spawning replacement worker...
2018-01-22 02:07:09 [master] Pool fork 5 died, spawning replacement worker...

/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:88
        throw e
              ^
Error: /usr/local/pool/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: _ZN5boost6system15system_categoryEv
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/pool/node_modules/cryptonote-util/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
2018-01-22 02:07:09 [master] Pool fork 2 died, spawning replacement worker...

/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:88
        throw e
              ^
Error: /usr/local/pool/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: _ZN5boost6system15system_categoryEv
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/pool/node_modules/cryptonote-util/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
2018-01-22 02:07:09 [master] Pool fork 8 died, spawning replacement worker...

/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:88
        throw e
              ^
Error: /usr/local/pool/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: _ZN5boost6system15system_categoryEv
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/pool/node_modules/cryptonote-util/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
2018-01-22 02:07:09 [master] Pool fork 7 died, spawning replacement worker...

/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:88
        throw e
              ^
Error: /usr/local/pool/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: _ZN5boost6system15system_categoryEv
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/pool/node_modules/cryptonote-util/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
2018-01-22 02:07:09 [master] Pool fork 6 died, spawning replacement worker...

/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:88
        throw e
              ^
Error: /usr/local/pool/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: _ZN5boost6system15system_categoryEv
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/pool/node_modules/cryptonote-util/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
2018-01-22 02:07:11 [master] Pool fork 4 died, spawning replacement worker...

/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:88
        throw e
              ^
Error: /usr/local/pool/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: _ZN5boost6system15system_categoryEv
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/pool/node_modules/cryptonote-util/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
2018-01-22 02:07:11 [master] Pool fork 1 died, spawning replacement worker...

/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:88
        throw e
              ^
Error: /usr/local/pool/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: _ZN5boost6system15system_categoryEv
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/pool/node_modules/cryptonote-util/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
2018-01-22 02:07:11 [master] Pool fork 3 died, spawning replacement worker...

/usr/local/pool/node_modules/cryptonote-util/node_modules/bindings/bindings.js:88
        throw e
              ^
Error: /usr/local/pool/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: _ZN5boost6system15system_categoryEv
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/pool/node_modules/cryptonote-util/node_modul
............

Can anyone help me to resolve it?

**Comment by xstalpha** [comment]
i had similar issues with ubuntu 16.04. try ubuntu 14.04
