### ISSUE TITLE
socket error while connecting miner

### ISSUE THREAD

**Issue by alexmateescu** [zone117x/node-cryptonote-pool#278]
Hi. I have setup your pool onto a new cryptocoin "Alloy (XAO)" and i am getting the following error when i am trying to connect the miner.

8|init     | Error: Failed to parse block
8|init     |     at Object.BlockTemplate.nextBlob (/home/alex/node-cryptonote-pool/lib/pool.js:128:23)
8|init     |     at Object.Miner.getJob (/home/alex/node-cryptonote-pool/lib/pool.js:301:41)
8|init     |     at handleMinerMethod (/home/alex/node-cryptonote-pool/lib/pool.js:511:28)
8|init     |     at handleMessage (/home/alex/node-cryptonote-pool/lib/pool.js:645:13)
8|init     |     at Socket.socket.on.on.on.pushMessage (/home/alex/node-cryptonote-pool/lib/pool.js:699:25)
8|init     |     at Socket.emit (events.js:95:17)
8|init     |     at Socket.<anonymous> (_stream_readable.js:765:14)
8|init     |     at Socket.emit (events.js:92:17)
8|init     |     at emitReadable_ (_stream_readable.js:427:10)
8|init     |     at emitReadable (_stream_readable.js:423:5)
8|init     | Error: Failed to parse block
8|init     |     at Object.BlockTemplate.nextBlob (/home/alex/node-cryptonote-pool/lib/pool.js:128:23)
8|init     |     at Object.Miner.getJob (/home/alex/node-cryptonote-pool/lib/pool.js:301:41)
8|init     |     at handleMinerMethod (/home/alex/node-cryptonote-pool/lib/pool.js:511:28)
8|init     |     at handleMessage (/home/alex/node-cryptonote-pool/lib/pool.js:645:13)
8|init     |     at Socket.socket.on.on.on.pushMessage (/home/alex/node-cryptonote-pool/lib/pool.js:699:25)
8|init     |     at Socket.emit (events.js:95:17)
8|init     |     at Socket.<anonymous> (_stream_readable.js:765:14)
8|init     |     at Socket.emit (events.js:92:17)
8|init     |     at emitReadable_ (_stream_readable.js:427:10)
8|init     |     at emitReadable (_stream_readable.js:423:5)
8|init     | 2018-01-29 09:29:32 [master] Pool fork 1 died, spawning replacement worker...
8|init     | 2018-01-29 09:29:34 [pool] (Thread 1) New block to mine at height 4014 w/ difficulty of 168679209

if i setup the pool on the cryptonote-universal-pool it is working and i was wondering if there could be something worng in the cryptonote-util package.

what could i look for in it ?

regards

**Comment by falcron11468** [comment]
Same issue, did you find a fix?  Tried a lot of suggestions online but not finding any working solutions for me.

**Comment by alexmateescu** [comment]
no. no solution yet

i have tried multiple things but none working.

**Comment by falcron11468** [comment]
I am searching, will post here if I find a solution.  Please do the same.

**Comment by Admiral-Noisy-Bottom** [comment]
If cryptonote-universal-pool was working, go back to it. Unless you have a good reason to change. There is alos forknote pool.
