### ISSUE TITLE
undefined symbol 

### ISSUE THREAD

**Issue by zezto** [zone117x/node-cryptonote-pool#334]
I was wondering if somebody could help me understand what packages I'm missing or what I'm doing wrong . I keep getting this error 
`/home/reglaptop/pool2/node_modules/cryptonote-util/node_modules/bindings/binding                                                                                                                                                             s.js:88
        throw e
        ^

Error: /home/reglaptop/pool2/node_modules/cryptonote-util/build/Release/cryptono                                                                                                                                                             te.node: undefined symbol: _ZN10cryptonote16get_block_rewardEjjyRy
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/home/reglaptop/pool2/node_modules/cryptonote-util/node_modules                                                                                                                                                             /bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/reglaptop/pool2/node_modules/cryptonote-util/in                                                                                                                                                             dex.js:1:99)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)`

**Comment by yinjiahjk** [comment]
我也是这个问题，有人能帮忙解决一下吗？
