### ISSUE TITLE
Miners cannot connect to pool

### ISSUE THREAD

**Issue by userid2018** [zone117x/node-cryptonote-pool#338]
Hello,

I installed a brand new pool using this guide 
http://prolinuxhub.com/setting-up-your-own-monero-mining-pool-with-node-cryptonote-pool-and-ubuntu-14/

Pool is up and the blockchain is synched but miners are not able to connect.

on running netstat --listen, i only see following tcp ports. None of the Mining ports (3333,5555,7777) are listed. is there anything missing or any steps to be performed to activate these ports?

tcp        0      0 localhost:6379          *:*                     LISTEN
tcp        0      0 *:25324                 *:*                     LISTEN
tcp        0      0 *:ssh                   *:*                     LISTEN
tcp        0      0 *:18080                 *:*                     LISTEN
tcp        0      0 localhost:18081         *:*                     LISTEN
tcp        0      0 localhost:18082         *:*                     LISTEN
tcp        0      0 localhost:mysql         *:*                     LISTEN
tcp6       0      0 [::]:http               [::]:*                  LISTEN
tcp6       0      0 [::]:8117               [::]:*                  LISTEN
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN

**Comment by userid2018** [comment]
An update 

I tried running "cryptonote-easy-miner  and started getting this error :: stratum_recv_line failed"

Following is the error message which is coming due to running of command node init.js


TypeError: buffArray.reverse is not a function
    at Object.Miner.getTargetHex (/opt/pool/lib/pool.js:288:19)
    at Object.Miner.getJob (/opt/pool/lib/pool.js:305:27)
    at handleMinerMethod (/opt/pool/lib/pool.js:514:28)
    at handleMessage (/opt/pool/lib/pool.js:648:13)
    at Socket.<anonymous> (/opt/pool/lib/pool.js:702:25)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

2018-06-12 16:07:36 [master] Pool fork 2 died, spawning replacement worker...
                                    2018-06-12 16:07:40 [pool] (Thread 4) New block to mine at height 1582706 w/ difficulty of 49740678932
2018-06-12 16:07:40 [unlocker] No blocks candidates in redis
2018-06-12 16:07:40 [pool] (Thread 1) New block to mine at height 1582706 w/ difficulty of 49740678932
2018-06-12 16:07:40 [api] Stat collection finished: 2 ms redis, 7706 ms daemon
2018-06-12 16:07:40 [api] Broadcasting to 8 visitors and 0 address lookups



Any help is appreciated.
