### ISSUE TITLE
new default settings pool error

### ISSUE THREAD

**Issue by AlekseiBo** [zone117x/node-cryptonote-pool#354]

**Comment by AlekseiBo** [comment]
Just followed the instructions and launched the pool. Got the following error on Ubuntu 16.04

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/alexbo/pool/node_modules/bignum/binding/bignum.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/alexbo/pool/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
2018-11-09 17:01:58 [master] Pool fork 1 died, spawning replacement worker...

Can someone advice what to do from here?
