### ISSUE TITLE
npm update error

### ISSUE THREAD

**Issue by xuebinboy** [zone117x/node-cryptonote-pool#89]
exec npm update

make: Leaving directory `/root/pool/node_modules/multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/pool/node_modules/multi-hashing
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! not ok code 0

what's Solution！！！ thanks..

**Comment by edilio** [comment]
That happened to me and I fixed it using node==0.10.

**Comment by zone117x** [comment]
https://github.com/zone117x/node-cryptonote-pool/issues/137
