### ISSUE TITLE
TypeError: Cannot set property '3' of undefined

### ISSUE THREAD

**Issue by mndmx31** [zone117x/node-cryptonote-pool#92]
TypeError: Cannot set property '3' of undefined
    at collectStats [as _onTimeout] lib/api.js:43:25
    at Timer.listOnTimeout [as ontimeout] timers.js:110:15

2015-09-30 09:55:45 [master] API died, spawning replacement...

**Comment by Fcases** [comment]
same here

**Comment by sammy007** [comment]
Same here, I am using old copy of node_modules for now. This is a problem in one of dependencies.

**Comment by Fcases** [comment]
You have a copy ?

**Comment by sammy007** [comment]
Try upgrade node-redis to 2.1.0 there is a bug fixed with argument mutation when using redis.multi. This should fix problem. Please report a result. Just run npm upgrade.

**Comment by sammy007** [comment]
If it does not work, please downgrade version and detect working one. Please report result here.

**Comment by sammy007** [comment]
Yeah, hardcode in package.json

<code>"redis": "0.12.1"</code>

**Comment by sammy007** [comment]
Quick fix in master. Pull changes and run <code>npm upgrade</code>.

**Comment by Fcases** [comment]
This starts, but now all my payments and fees are NAN in stats.. weird,

**Comment by sammy007** [comment]
What is your setup? I am using slightly modified version of this pool and this fix works for me like a charm.

**Comment by sammy007** [comment]
node 0.10.40, node-redis 0.12.1. Delete node_modules and run npm update again. It must work.

**Comment by sammy007** [comment]
Also, i am running redis-server 2.8.4.

**Comment by Fcases** [comment]
Yes it works BUT, like I said before the fix, it messed my REDIS I think all amount and fee = nan in payments tab… any idea ?

**Comment by sammy007** [comment]
Is it fresh setup? If yes, then it's maybe ok, I can't remember actually how it goes on fresh setup without any data in redis.

**Comment by Fcases** [comment]
No its:

Had issues with payments not going out..
So I regitted the source in a new dir
Copied my config from old dir to new dir

Ran.. it fucked redis..

Re got the soure

Applied the redis 0.12.1

Reran..

All shows as NAN

**Comment by sammy007** [comment]
No idea. I fall into this issue by upgrading server and running npm update. I noticed bug from the title, so I downgraded redis and it works for me now. No idea, try to add additional <code>hiredis</code> parser right before <code>redis</code>. I am not sure I am right and even not talking bullshit, cuz I have no time to play with different setups, etc at this time. Just some guesses. Redis downgrade can't fuck your data, I am using it on my production hashinvest.net.

**Comment by Fcases** [comment]
Nah something else did… also the admin not working no more… this is a clean install even tried on a clean db.
